InvitationBundle\Entity\Action:
    type: entity
    table: null
    repositoryClass: InvitationBundle\Repository\ActionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        tag:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    manyToMany:
        eventRoles:
            targetEntity: EventRole
            mappedBy: actions
    manyToOne:
        nameTranslation:
            targetEntity: AppBundle\Entity\Translation
            joinColumn:
                name: translation_id
                referencedColumnName: id
                nullable: true