InvitationBundle\Entity\EventRole:
    type: entity
    table: null
    repositoryClass: InvitationBundle\Repository\EventRoleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        specialName:
            type: string
            length: 32
            nullable: true
            column: special_name
    lifecycleCallbacks: {  }
    manyToMany:
        actions:
            targetEntity: Action
            inversedBy: eventRoles
            joinTable:
                name: action_event_role
                joinColumns:
                    event_role_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    action_id:
                        referencedColumnName: id
    manyToOne:
        nameTranslation:
            targetEntity: AppBundle\Entity\Translation
            joinColumn:
                name: translation_id
                referencedColumnName: id
                nullable: true
    oneToMany:
        eventAggr:
            targetEntity: UserEventRoleEvent
            mappedBy: eventRole