InvitationBundle\Entity\EventType:
    type: entity
    table: null
    repositoryClass: InvitationBundle\Repository\EventTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        title:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
