InvitationBundle\Entity\Invitation:
    type: entity
    table: null
    repositoryClass: InvitationBundle\Repository\InvitationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        urlName:
            type: string
            length: 255
            unique: true
            column: url_name
        email:
            type: string
            length: 255
            nullable: true
        phone:
            type: string
            length: 255
            nullable: true
        code:
            type: integer
            unique: true
        addDate:
            type: datetime
            column: add_date
        lastChange:
            type: datetime
            column: last_change
        status:
            type: integer
        innerOrder:
            type: integer
            column: inner_order
    lifecycleCallbacks: {  }
