InvitationBundle\Entity\InvitationGroup:
    type: entity
    table: null
    repositoryClass: InvitationBundle\Repository\InvitationGroupRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        urlName:
            type: string
            length: 255
            column: url_name
        color:
            type: string
            length: '7'
            nullable: true
    lifecycleCallbacks: {  }
    oneToMany:
        invitation:
            targetEntity: Invitation
            mappedBy: invitationGroup
    manyToOne:
        event:
            targetEntity: Event
            inversedBy: invitationGroup
            joinColumn:
                name: event_id
                referencedColumnName: id