InvitationBundle\Entity\Invitation:
    type: entity
    table: null
    repositoryClass: InvitationBundle\Repository\InvitationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        urlName:
            type: string
            length: 255
            unique: true
            column: url_name
        email:
            type: string
            length: 255
            nullable: true
        phone:
            type: string
            length: 255
            nullable: true
        code:
            type: integer
            unique: true
        status:
            type: integer
        innerOrder:
            type: integer
            column: inner_order
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    lifecycleCallbacks:
        prePersist: [ fillEmptyFields ]
        preUpdate: [ beforeUpdate ]
    oneToMany:
        person:
            targetEntity: Person
            mappedBy: invitation
        changelog:
            targetEntity: Changelog
            mappedBy: invitation
        message:
            targetEntity: Message
            mappedBy: invitation
    manyToOne:
        invitationGroup:
            targetEntity: InvitationGroup
            inversedBy: invitation
            joinColumn:
                name: invitation_group_id
                referencedColumnName: id
                nullable: true
        event:
            targetEntity: Event
            inversedBy: invitation
            joinColumn:
                name: event_id
                referencedColumnName: id