InvitationBundle\Entity\Parameter:
    type: entity
    table: null
    repositoryClass: InvitationBundle\Repository\ParameterRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        type:
            type: string
            length: 16
        description:
            type: string
            length: 2048
            nullable: true
        typeConfig:
            type: text
            nullable: true
            column: type_config
        innerOrder:
            type: integer
            column: inner_order
            nullable: true
    lifecycleCallbacks: {  }
    manyToOne:
        predefiniedParameter:
            targetEntity: PredefiniedParameter
            inversedBy: parameter
            joinColumn:
                name: predefinied_parameter_id
                referencedColumnName: id
                nullable: true
        event:
            targetEntity: Event
            inversedBy: parameter
            joinColumn:
                name: event_id
                referencedColumnName: id
    oneToMany:
        parameterValue:
            targetEntity: ParameterValue
            mappedBy: parameter