InvitationBundle\Entity\PersonGroup:
    type: entity
    table: null
    repositoryClass: InvitationBundle\Repository\PersonGroupRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        price:
            type: float
        color:
            type: string
            length: 7
            nullable: true
    lifecycleCallbacks: {  }
    oneToMany:
        person:
            targetEntity: Person
            mappedBy: personGroup
    manyToOne:
        event:
            targetEntity: Event
            inversedBy: personGroup
            joinColumn:
                name: event_id
                referencedColumnName: id