InvitationBundle\Entity\PredefiniedParameter:
    type: entity
    table: null
    repositoryClass: InvitationBundle\Repository\PredefiniedParameterRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        type:
            type: string
            length: '16'
    lifecycleCallbacks: {  }
    oneToMany:
        parameter:
            targetEntity: Parameter
            mappedBy: predefiniedParameter