panel_person_manager:
    path:     /personManager
    defaults: { _controller: PanelBundle:PersonManager:index }

panel_event_manager:
    path:     /
    defaults: { _controller: PanelBundle:EventManager:index }

index:
    path:     /event/{slug}
    defaults: { _controller: PanelBundle:EventDashboard:index }
