panel_event_manager:
    path:     /
    defaults: { _controller: PanelBundle:EventManager:index }

panel_event_manager_delete:
    path:     /event/delete/{slug}
    defaults: { _controller: PanelBundle:EventManager:delete }

panel_event_dashboard:
    path:     /event/{slug}
    defaults: { _controller: PanelBundle:EventDashboard:index }
    
panel_invitations_manager:
    path:     /invitation/{slug}/{page}
    defaults: { _controller: PanelBundle:InvitationsManager:index, page:1 }
    requirements:
        page:     \d+
    
panel_invitations_manager_add_invitation:
    path:     /invitation/{slug}/addInvitation
    defaults: { _controller: PanelBundle:InvitationsManager:addInvitation }
    
panel_invitations_manager_remove_invitation:
    path:     /invitation/{slug}/removeInvitation/{invitation}
    defaults: { _controller: PanelBundle:InvitationsManager:removeInvitation }

panel_invitations_manager_invitation:
    path:     /invitation/{slug}/edit/{invitation}
    defaults: { _controller: PanelBundle:InvitationEditor:index }
    requirements:
        invitation:     \d+

panel_event_config:
    path:     /event/{slug}/config
    defaults: { _controller: PanelBundle:EventConfig:index }

panel_event_config_type_config:
    path:  /event/typeConfig/{type}/{output}
    defaults: { _controller: PanelBundle:EventConfig:typeConfig }
    options:
        expose: true

panel_event_generator:
    path:     /generator/{slug}
    defaults: { _controller: PanelBundle:Generator:index }

panel_event_news:
    path:     /news/{slug}/
    defaults: { _controller: PanelBundle:News:index }

panel_event_news_create:
    path:     /news/{slug}/create
    defaults: { _controller: PanelBundle:News:create }
    
panel_event_news_edit:
    path:     /news/{slug}/edit/{newsSlug}
    defaults: { _controller: PanelBundle:News:edit }
    
panel_event_news_remove:
    path:     /news/{slug}/remove/{newsSlug}
    defaults: { _controller: PanelBundle:News:remove }
    options:
        expose: true

panel_my_account:
    path:     /account
    defaults: { _controller: PanelBundle:Account:index }

#Generators

panel_event_generator_PDF_stickers:
    path:     /generator/{slug}/PDF/stickers/{filename}.{_format}
    defaults: { _controller: PanelBundle:Generator:generateStickers}

panel_event_generator_PDF_vignette:
    path:     /generator/{slug}/PDF/vignette/{filename}.{_format}
    defaults: { _controller: PanelBundle:Generator:generateVignette}

panel_event_generator_XLS_list:
    path:     /generator/{slug}/XLS/list/{filename}.{_format}
    defaults: { _controller: PanelBundle:Generator:generateExcelList}

person:
    path:     /person
    defaults: { _controller: PanelBundle:Report:person }

invitation:
    path:     /invitation
    defaults: { _controller: PanelBundle:Report:invitation }

changelog:
    path:     /changelog
    defaults: { _controller: PanelBundle:Report:changelog }
