panel_event_manager:
    path:     /
    defaults: { _controller: PanelBundle:EventManager:index }

panel_event_dashboard:
    path:     /event/{slug}
    defaults: { _controller: PanelBundle:EventDashboard:index }
    
panel_invitations_manager:
    path:     /invitations/{slug}
    defaults: { _controller: PanelBundle:InvitationsManager:index }
    
panel_invitations_manager_add_invitation:
    path:     /invitations/{slug}/addInvitation
    defaults: { _controller: PanelBundle:InvitationsManager:addInvitation }
