panel_event_manager:
    path:     /
    defaults: { _controller: PanelBundle:EventManager:index }

panel_event_manager_delete:
    path:     /event/delete/{slug}
    defaults: { _controller: PanelBundle:EventManager:delete }

panel_event_dashboard:
    path:     /event/{slug}
    defaults: { _controller: PanelBundle:EventDashboard:index }
    
panel_invitations_manager:
    path:     /invitation/{slug}/{page}
    defaults: { _controller: PanelBundle:InvitationsManager:index, page:1 }
    requirements:
        page:     \d+
    
panel_invitations_manager_add_invitation:
    path:     /invitation/{slug}/addInvitation
    defaults: { _controller: PanelBundle:InvitationsManager:addInvitation }
    
panel_invitations_manager_remove_invitation:
    path:     /invitation/{slug}/removeInvitation/{invitation}
    defaults: { _controller: PanelBundle:InvitationsManager:removeInvitation }

panel_invitations_manager_invitation:
    path:     /invitation/{slug}/edit/{invitation}
    defaults: { _controller: PanelBundle:InvitationEditor:index }
    requirements:
        invitation:     \d+

panel_event_config:
    path:     /event/{slug}/config
    defaults: { _controller: PanelBundle:EventConfig:index }

panel_event_config_type_config:
    path:  /event/typeConfig/{type}/{output}
    defaults: { _controller: PanelBundle:EventConfig:typeConfig }
    options:
        expose: true