<?php

namespace AppBundle\Repository;

/**
 * LanguageTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
