<?php

namespace AppBundle\Repository;

/**
 * TransactionValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationValueRepository extends \Doctrine\ORM\EntityRepository
{
}
