invitation:
    resource: "@InvitationBundle/Resources/config/routing.yml"
    prefix:   /
    host:     "www.{slug}.{domain}"
    defaults:
        domain: '%domain%'
    requirements:
        domain: '%domain%'

panel:
    resource: "@PanelBundle/Resources/config/routing.yml"
    prefix:   /panel
    host:     "www.{domain}"
    defaults:
        domain: '%domain%'
    requirements:
        domain: '%domain%'
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
    host:     "www.{domain}"
    defaults:
        domain: '%domain%'
    requirements:
        domain: '%domain%'
# FOS User routings:
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"