# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        ROLE_GUEST
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        invitation_provider:
            id: invitation.auhenticator

    firewalls:
        panel:
            host: %domain%
            #pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: panel_event_manager
            logout:       true
            anonymous:    true
        invitation:
            host: ^*\.%domain%
            http_basic: ~
            provider: invitation_provider
            #pattern: ^/invitation

    access_control:
        - { path: ^/panel/, role: ROLE_USER }
        - { path: ^/invitation/, role: ROLE_GUEST }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }