# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
services:
    invitation.auhenticator:
        class: InvitationBundle\Security\InvitationProvider
        arguments: [ "@doctrine.orm.entity_manager" ]
    invitation.recorder:
        class: InvitationBundle\Services\Recorder\Recorder
        arguments: [ "@doctrine.orm.entity_manager", "@security.token_storage", "@request_stack" ]
        