invitation_dashboard:
    path:     /
    defaults: { _controller: InvitationBundle:Dashboard:index }

invitation_confirmator:
    path:     /confirmator
    defaults: { _controller: InvitationBundle:Confirmator:index }

invitation_personal_data:
    path:     /personalData
    defaults: { _controller: InvitationBundle:PersonalData:index }