InvitationBundle\Entity\InvitationGroup:
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 255
        color:
            - Length:
                max: 7
InvitationBundle\Entity\Event:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: urlName
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
        urlName:
            - Length:
                min: 3
                max: 32
            - Regex:
                pattern: '/^[a-z0-9_-]+$/'
                message: event.urlName.invalidChars
InvitationBundle\Entity\Invitation:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 1
                max: 255
        email:
            - Length:
                max: 255
            - Email:
                checkMX: true
        phone:
            - Length:
                max: 255
InvitationBundle\Entity\Person:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 1
                max: 255
InvitationBundle\Entity\News:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [urlName, event]
    properties:
        content:
            - NotBlank: ~
        title:
            - NotBlank: ~
            - Length:
                min: 3
                max: 1024
        urlName:
            - Length:
                min: 3
                max: 128
            - Regex:
                pattern: '/^[a-z0-9_-]+$/'
                message: event.urlName.invalidChars