AppBundle\Entity\LanguageTranslation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\LanguageTranslationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        catalogue:
            type: string
            length: 255
        translation:
            type: text
    lifecycleCallbacks: {  }
    manyToOne:
        language:
            targetEntity: Language
            joinColumn:
                name: language_id
                referencedColumnName: id
        languageToken:
            targetEntity: LanguageToken
            joinColumn:
                name: language_token_id
                referencedColumnName: id
