AppBundle\Entity\Language:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\LanguageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        locale:
            type: string
            length: 255
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
