<?php

namespace InvitationBundle\Repository;

/**
 * ChangelogDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangelogDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
