<?php

namespace InvitationBundle\Repository;

use InvitationBundle\Entity\Event;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository {
    public function findByRelatedUser( $User ) {
        $query = $this->getEntityManager()
        ->createQuery(
            'SELECT e, a FROM InvitationBundle:Event e
            JOIN e.eventAggr a
            WHERE a.userId = :userId AND e.status IN (:goodStat)' 
        )->setParameters([
            'userId' => $User->getId(),
            'goodStat' => [
                Event::STATUS_ENABLED,
            ]
        ]);
        return $query->getResult();
    }
}
