<?php

namespace InvitationBundle\Repository;

/**
 * EventTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTypeRepository extends \Doctrine\ORM\EntityRepository {
    
}
