<?php

namespace InvitationBundle\Repository;

/**
 * EventRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
