<?php

namespace InvitationBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository {
    public function findByRelatedUser( $User ) {
        $query = $this->getEntityManager()
        ->createQuery(
            'SELECT e, a FROM InvitationBundle:Event e
            JOIN e.eventAggr a
            WHERE a.userId = :userId'
        )->setParameter('userId', $User->getId());
        return $query->getResult();
    }
}
