<?php

namespace InvitationBundle\Repository;

/**
 * InvitationGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
