<?php

namespace InvitationBundle\Repository;

/**
 * ParameterValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterValueRepository extends \Doctrine\ORM\EntityRepository
{
}
