<?php

namespace InvitationBundle\Repository;

/**
 * PersonGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
