<?php

namespace InvitationBundle\Repository;

/**
 * PredefiniedParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredefiniedParameterRepository extends \Doctrine\ORM\EntityRepository
{
}
