<?php

namespace InvitationBundle\Repository;

/**
 * UserEventRoleEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEventRoleEventRepository extends \Doctrine\ORM\EntityRepository
{
}
